<div class="row">
    <div class="col-12 py-5 text-center">
        <h1>
            Package Manager Presentation - InsanityMeetsHH 
            <a href="https://github.com/InsanityMeetsHH/pm-presentation" target="_blank"><i class="fab fa-inverse fa-github" aria-hidden="true" data-toggle="tooltip" data-placement="bottom" title="GitHub"></i></a>
        </h1>
    </div>
</div>
<div class="row text-center justify-content-center">
    <div class="col-12 col-lg-8 pb-5">
        <div class="slider slider-brands">
            <div class="slider-item px-5">
                <h2>Was sind Package Manager?</h2>
                <p>
                    Eine Softwarepaket-Verwaltung ermöglicht die komfortable 
                    Verwaltung von Software, die in Programmpaketform vorliegt, 
                    auf einem System. Dazu gehören das Installieren, Aktualisieren und Deinstallieren.
                </p>
                <p>
                    Ich benutze <a href="https://nodejs.org/de/" target="_blank">Node.js</a> (<a href="https://www.npmjs.com/" target="_blank">NPM</a>) für JS/CSS 
                    und <a href="https://getcomposer.org/" target="_blank">Composer</a> (<a href="https://packagist.org/" target="_blank">Packagist</a>) für PHP.
                </p>
            </div>
            <div class="slider-item px-5">
                <h2>Vorteile</h2>
                <ul>
                    <li>Herunterladen und Installieren über standard oder definierte Repositories</li>
                    <li>Installieren mit berücksichtigung von Abhängigkeiten</li>
                    <li>Verschlankung von Git/SVN-Repositories</li>
                    <li>Packete liegen in einem definierten Ordner</li>
                    <li>Einfacher Versionswechsel von Packeten (Install / Update / Revert)</li>
                </ul>
            </div>
            <div class="slider-item px-5">
                <h2>Quellen</h2>
                <p>
                    <a href="https://de.wikipedia.org/wiki/Paketverwaltung" target="_blank">Paketverwaltung Wiki</a><br/>
                    <a href="https://php-de.github.io/jumpto/composer/" target="_blank">Composer Tutorial</a><br/>
                    <a href="https://www.norberteder.com/node-package-manager-und-package-json/" target="_blank">NPM Tutorial</a><br/>
                    <a href="https://github.com/InsanityMeetsHH/Slim-Skeleton" target="_blank">Composer Beispiel (Slim Skeleton)</a><br/>
                    <a href="https://github.com/InsanityMeetsHH/gulp-templating" target="_blank">NPM Beispiel (Gulp Templating)</a>
                </p>
            </div>
        </div>
    </div>
</div>
